# Generated by Django 5.0.2 on 2024-02-23 09:15

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chef_position', models.TextField(blank=True)),
                ('about', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(upload_to='chefs/')),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Chefs',
                'ordering': ('position',),
            },
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^\\+?380\\d{9}$', 'Phone number must be entered in the format: "+380xxxxxxxxx".')]),
        ),
    ]
