# Generated by Django 5.0.2 on 2024-02-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_chef_alter_reservation_email_alter_reservation_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='events/')),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ('position',),
            },
        ),
    ]
