# Generated by Django 5.0.2 on 2024-02-23 12:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('opening_hours_mon_fri', ckeditor.fields.RichTextField()),
                ('opening_hours_sat_sun', ckeditor.fields.RichTextField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
